"""Added is_hidden to comments, products, review

Revision ID: 063efb53fff4
Revises: a4e89935ce3d
Create Date: 2023-03-04 13:19:06.592241

"""
from alembic import op
import sqlalchemy as sa


revision = '063efb53fff4'
down_revision = 'a4e89935ce3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('is_hidden', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('is_hidden', sa.Boolean(), nullable=True))
    op.add_column('reviews', sa.Column('is_hidden', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'is_hidden')
    op.drop_column('products', 'is_hidden')
    op.drop_column('comments', 'is_hidden')
    # ### end Alembic commands ###
