"""Trying to fix bugs

Revision ID: 06fd07665b92
Revises: b21830de2e69
Create Date: 2023-03-05 19:43:22.027472

"""
from alembic import op
import sqlalchemy as sa


revision = '06fd07665b92'
down_revision = 'b21830de2e69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('product_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'comments', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'product_id')
    # ### end Alembic commands ###
