"""Fixed useless nullable

Revision ID: 3b181c524e82
Revises: 8ec70f8cea2b
Create Date: 2023-03-04 22:05:10.230475

"""
from alembic import op
import sqlalchemy as sa


revision = '3b181c524e82'
down_revision = '8ec70f8cea2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'likes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'likes',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'likes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comments', 'likes',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
