"""Added bio column into user model

Revision ID: 7e9d396efb77
Revises: 
Create Date: 2022-12-11 13:30:02.657103

"""
from alembic import op
import sqlalchemy as sa


revision = '7e9d396efb77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
