"""Refactoring

Revision ID: 802ac1d20267
Revises: e9636efcc1ae
Create Date: 2023-03-06 17:01:02.664487

"""
from alembic import op
import sqlalchemy as sa


revision = '802ac1d20267'
down_revision = 'e9636efcc1ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('permission_id', sa.BigInteger(), nullable=False))
    op.drop_constraint('groups_name_key', 'groups', type_='unique')
    op.create_foreign_key(None, 'groups', 'permissions', ['permission_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.create_unique_constraint('groups_name_key', 'groups', ['name'])
    op.drop_column('groups', 'permission_id')
    # ### end Alembic commands ###
