"""Added more proper foreign keys to user table

Revision ID: 8ec70f8cea2b
Revises: 063efb53fff4
Create Date: 2023-03-04 21:57:35.153633

"""
from alembic import op
import sqlalchemy as sa


revision = '8ec70f8cea2b'
down_revision = '063efb53fff4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'author_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('reviews', 'author_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.add_column('sellers', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'sellers', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('permission_id', sa.BigInteger(), nullable=False))
    op.add_column('users', sa.Column('seller_id', sa.BigInteger(), nullable=True))
    op.alter_column('users', 'is_stuff',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_foreign_key(None, 'users', 'permissions', ['permission_id'], ['id'])
    op.create_foreign_key(None, 'users', 'sellers', ['seller_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'is_stuff',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('users', 'seller_id')
    op.drop_column('users', 'permission_id')
    op.drop_constraint(None, 'sellers', type_='foreignkey')
    op.drop_column('sellers', 'user_id')
    op.alter_column('reviews', 'author_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('comments', 'author_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
