"""Added saling into passwords

Revision ID: d27323a2092a
Revises: 7e9d396efb77
Create Date: 2022-12-16 18:57:41.747442

"""
from alembic import op
import sqlalchemy as sa


revision = 'd27323a2092a'
down_revision = '7e9d396efb77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('salt', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'salt')
    # ### end Alembic commands ###
