"""Omg...

Revision ID: e9636efcc1ae
Revises: 06fd07665b92
Create Date: 2023-03-06 16:44:27.876258

"""
from alembic import op
import sqlalchemy as sa


revision = 'e9636efcc1ae'
down_revision = '06fd07665b92'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_entities_users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=52), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('offset', sa.Integer(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_text_entities_users_id'), 'text_entities_users', ['id'], unique=True)
    op.create_table('text_entities_products',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=52), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('offset', sa.Integer(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_text_entities_products_id'), 'text_entities_products', ['id'], unique=True)
    op.create_table('text_entities_reviews',
    sa.Column('review_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=52), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('offset', sa.Integer(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_text_entities_reviews_id'), 'text_entities_reviews', ['id'], unique=True)
    op.create_table('text_entities_comments',
    sa.Column('comment_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=52), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('offset', sa.Integer(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_text_entities_comments_id'), 'text_entities_comments', ['id'], unique=True)
    op.drop_index('ix_text_entities_id', table_name='text_entities')
    op.drop_table('text_entities')
    op.alter_column('products', 'seller_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'seller_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_table('text_entities',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(length=52), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('offset', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('length', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='text_entities_pkey')
    )
    op.create_index('ix_text_entities_id', 'text_entities', ['id'], unique=False)
    op.drop_index(op.f('ix_text_entities_comments_id'), table_name='text_entities_comments')
    op.drop_table('text_entities_comments')
    op.drop_index(op.f('ix_text_entities_reviews_id'), table_name='text_entities_reviews')
    op.drop_table('text_entities_reviews')
    op.drop_index(op.f('ix_text_entities_products_id'), table_name='text_entities_products')
    op.drop_table('text_entities_products')
    op.drop_index(op.f('ix_text_entities_users_id'), table_name='text_entities_users')
    op.drop_table('text_entities_users')
    # ### end Alembic commands ###
